    
logging:
  level:
    org:
      atmosphere: warn
server:
  port: ${PORT:8080}
spring:
  mustache:
    check-template-location: false
    
  data:
    mongodb:
      #database: vaadin-mongo-test
      #host: localhost
      #uri: mongodb://localhost:27017/vaadin-mongo-test
      #https://dev.to/damcosset/setting-up-a-replica-set-in-mongodb
      uri: mongodb://localhost:27017,localhost:27018,localhost:27019/vaadin-mongo-test
  servlet:
    multipart:
      max-file-size: 100000000
      max-request-size: 100000000
    
